server:
  port: 8888


spring:
  application:
    name: kecleon
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Glup3/sollhaben
          default-label: main
          searchPaths: config